fix: Add a shebang and a minor refactor
3 Changes:

1. Add a shebang because I get the following error while scaffolding:
```
Traceback (most recent call last):
  File "/tmp/tmpEn2PdS.py", line 2, in <module>
    from shutil import which
ImportError: cannot import name which
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```
2. removed unused version_info
3. `if item not in items` is more pythonic usage.